name: Deployment Pipeline

on:
  push:
    branches:
      - migrate-to-node
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint:fix && npm run lint

      - name: Run prettier
        run: npm run prettier:fix && npm run prettier

      - name: Build project
        run: npm run build
